# Assignment 3 – Regression Dataset Preparation

This is Assignment 3 for the Introduction to Deep Learning with PyTorch course (www.leaky.ai).  

In this assignment you will practice preparing a real-world dataset for training a neural network.  You will be dealing with missing items, variable ranges in the input data as well as categorical text features.

Finally, when training neural networks, instead of processing one input at a time, it’s usually better to process a batch of inputs at the same time.  This leads to better training results and enables us to take advantage of parallel computing to accelerate the calculations.  But how do we create batches of input data?  The good news that PyTorch includes a dataset and dataloader object that automatically creates batches of the input data for the training process.  Once the dataset is ready, all we have to do is wrap it into a dataset object and pass that to our dataloader object.   You will practice this technique towards the end of the assignment.

### To Get Started
1.	Open up a web browser (preferable Chrome)
2.	Copy the Project GitHub Link: https://github.com/LeakyAI/PyTorch-Overview
3.	Head over to Google Colab (https://colab.research.google.com)
4.	Load the notebook: <b>Assignment 3 – Regression Dataset Preparation - Start Here.ipynb</b>
5.	Replace the [TBD]'s with your own code
6.	Execute the notebook after completing each cell and check your answers using the solution notebook

Good Luck!




## Part 1 - Standardization and Min Max Normalization

In [1]:
# Import PyTorch and set the seed for reproducible results
import torch
torch.manual_seed(6)

In [2]:
# Create a PyTorch tensor with the following content
# [[1,100,3,0.01,5000],[0,10,8,-0.002,0.01],[1,25,13,0.04,0.2],[1,45,18,-0.05,0.5]]
a = torch.tensor([[1,100,3,0.01,5000],[0,10,8,-0.002,0.01],[1,25,13,0.04,0.2],[1,45,18,-0.05,0.5]], dtype=torch.float)
torch.set_printoptions(precision=3,sci_mode=False)
print (a)

tensor([[     1.000,    100.000,      3.000,      0.010,   5000.000],
        [     0.000,     10.000,      8.000,     -0.002,      0.010],
        [     1.000,     25.000,     13.000,      0.040,      0.200],
        [     1.000,     45.000,     18.000,     -0.050,      0.500]])


# Normalize the Values
Here you will apply Max Min Normalization to the column values.

In [3]:
# find the max
maximums = a.max(axis=0)
print (maximums.values)

tensor([    1.000,   100.000,    18.000,     0.040,  5000.000])


In [4]:
# find the minimums
minimums = a.min(axis=0)
print (minimums.values)

tensor([     0.000,     10.000,      3.000,     -0.050,      0.010])


In [5]:
# Normalize A
aNormalized = (a - minimums.values) / (maximums.values - minimums.values)
print (aNormalized)

tensor([[    1.000,     1.000,     0.000,     0.667,     1.000],
        [    0.000,     0.000,     0.333,     0.533,     0.000],
        [    1.000,     0.167,     0.667,     1.000,     0.000],
        [    1.000,     0.389,     1.000,     0.000,     0.000]])


## Standardize the Values
Use the following formula:
xStandardized = (x - xMean) / xStdDeviation

In [14]:
# Calculate the mean and standard deviation of each column
xMean = a.mean(axis = 0)
#printf ("Mean: {xMean}")
python.__version__

NameError: name 'python' is not defined