# Tensor Assingment

This is the PyTorch tensor assingment for the leaky.ai Introduction to Deep Learning with PyTorch course (www.leaky.ai).  

To execute this assingment head over to Google Colab and load the notebook.

DIRECTIONS
1.  Load notebook into colab.research.google.com
2.  Execute the notebook after completing each cell

In [1]:
# Import PyTorch and check the version
import torch
torch.__version__

'1.7.1'

Correct Answer:  
```
'1.8.1'
```

# Creating Tensors
Lets create a few tensors that we will use for the remaining part of the exercise

In [2]:
# Create 2 PyTorch tensors with the following content and print them out:
# Tensor a should contain [1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0]
# Tensor b should contain [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]

# ---------- FILL IN BELOW -----------
a = torch.tensor([1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0])
b = torch.tensor([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print (a)
print (b)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])


## Section 2 - Processing Output of a Classifier
Here we have a sample output of an image classifer.  Note, these outputs are the logits and have not been converted into probabilities.  This classifer is being trained using a batch size of 32 and predicting one of 5 different classes.

In [17]:
# Execute this cell
pred = torch.tensor([[ 0.9293,  0.2901, -1.0152,  0.7746,  0.3067],
        [ 0.6137,  0.2334, -1.4214,  0.1945,  1.3687],
        [-0.5178, -0.2447, -1.6277,  0.3823, -1.7650],
        [-0.7128,  0.1357, -0.7442, -0.0554,  0.2912],
        [ 0.2781,  0.1012, -0.3719,  0.0612, -0.8098],
        [-0.5228,  0.7324, -0.5130,  0.1524, -1.0955],
        [-0.9477,  1.5931,  1.4148,  0.3352,  0.1616],
        [-0.8468,  0.4508, -0.0220,  0.5912, -1.2848],
        [-1.1751, -1.0395,  1.0125, -1.7792,  1.0216],
        [ 0.1302, -0.2518, -0.1261,  0.1736,  0.0854],
        [ 1.2633, -0.2371,  0.5904,  1.4261,  0.0923],
        [ 0.2116,  0.9561, -1.9999,  0.1392,  0.2477],
        [-0.4957, -1.0055,  0.0415, -0.5349,  0.1649],
        [ 0.6049, -0.9726, -1.5090, -0.2382, -0.7545],
        [-2.3070, -0.7316, -0.0962, -0.0539, -0.0683],
        [-0.1294, -0.8661,  0.7598,  2.3836, -1.5560],
        [ 0.6390, -0.7030, -1.3076,  0.3535, -0.8919],
        [-0.7093,  0.5825,  0.5225,  0.5499,  0.3741],
        [ 0.6182, -0.1380,  1.9645, -0.0651, -1.4204],
        [-1.0245, -0.7844,  0.4350, -0.3211, -1.6331],
        [-1.2897, -0.6440,  0.9762, -0.1727,  0.0712],
        [-0.0157, -2.0290,  0.8639,  0.6300, -0.3400],
        [ 0.4906, -1.4236, -0.0596,  0.9910,  0.0717],
        [-0.5555, -0.3457,  0.1960,  0.6476,  0.9825],
        [-0.4151,  0.9131,  0.1305,  0.9716, -1.2125],
        [-0.0460, -1.9476,  0.4115, -0.8822, -0.8379],
        [ 2.0143,  0.9110,  0.0745,  0.2747, -0.3691],
        [-1.4767,  0.7810,  0.3173, -1.6166, -1.6816],
        [ 1.6299, -0.2888,  0.3351,  1.8702, -0.1816],
        [ 0.4609,  0.2472,  1.0285,  0.4368,  0.7801],
        [ 0.1570, -0.6358,  1.3822, -0.5491, -0.2764],
        [-1.3916, -0.0608, -0.6357, -2.3946,  0.2521]])

In [19]:
# What is the shape of the output tensor?

# Type your answer here
pred.shape

torch.Size([32, 5])

Correct Answer:
```
torch.Size([32, 5])
```

In [31]:
# Create a Tensor which holds the probability of the highest value and assocaited index for each prediction
predProbability = torch.nn.functional.softmax(pred,dim=1)

print (predProbability[3])
prob, idx = torch.topk(predProbability,1)
print (prob)
print (idx)

tensor([0.1116, 0.2606, 0.1081, 0.2153, 0.3045])
tensor([[0.3264],
        [0.4626],
        [0.4563],
        [0.3045],
        [0.2856],
        [0.4360],
        [0.4101],
        [0.3570],
        [0.4366],
        [0.2343],
        [0.3655],
        [0.4063],
        [0.3118],
        [0.4964],
        [0.2811],
        [0.7483],
        [0.4216],
        [0.2502],
        [0.6462],
        [0.4709],
        [0.4943],
        [0.3903],
        [0.4091],
        [0.3773],
        [0.3654],
        [0.4370],
        [0.5736],
        [0.5236],
        [0.4453],
        [0.2978],
        [0.5675],
        [0.4154]])
tensor([[0],
        [4],
        [3],
        [4],
        [0],
        [1],
        [1],
        [3],
        [4],
        [3],
        [3],
        [1],
        [4],
        [0],
        [3],
        [3],
        [0],
        [1],
        [2],
        [2],
        [2],
        [2],
        [3],
        [4],
        [3],
        [2],
        [0],
        [1],
        [3

Correct Answer:
```
torch.Size([10]) torch.FloatTensor
torch.Size([4, 5]) torch.LongTensor
```

In [4]:
# Print out the last item in tensor A and B as a scalar (not tensor)
print (a.size(),a.type())
print (b.size(),b.type())

print(a[-1].item())
print(b[-1,-1].item())


10.0
20


In [16]:
a = torch.randn(32,5)
a

tensor([[ 0.9293,  0.2901, -1.0152,  0.7746,  0.3067],
        [ 0.6137,  0.2334, -1.4214,  0.1945,  1.3687],
        [-0.5178, -0.2447, -1.6277,  0.3823, -1.7650],
        [-0.7128,  0.1357, -0.7442, -0.0554,  0.2912],
        [ 0.2781,  0.1012, -0.3719,  0.0612, -0.8098],
        [-0.5228,  0.7324, -0.5130,  0.1524, -1.0955],
        [-0.9477,  1.5931,  1.4148,  0.3352,  0.1616],
        [-0.8468,  0.4508, -0.0220,  0.5912, -1.2848],
        [-1.1751, -1.0395,  1.0125, -1.7792,  1.0216],
        [ 0.1302, -0.2518, -0.1261,  0.1736,  0.0854],
        [ 1.2633, -0.2371,  0.5904,  1.4261,  0.0923],
        [ 0.2116,  0.9561, -1.9999,  0.1392,  0.2477],
        [-0.4957, -1.0055,  0.0415, -0.5349,  0.1649],
        [ 0.6049, -0.9726, -1.5090, -0.2382, -0.7545],
        [-2.3070, -0.7316, -0.0962, -0.0539, -0.0683],
        [-0.1294, -0.8661,  0.7598,  2.3836, -1.5560],
        [ 0.6390, -0.7030, -1.3076,  0.3535, -0.8919],
        [-0.7093,  0.5825,  0.5225,  0.5499,  0.3741],
        [ 

Correct Answer:
```
10.0
20
```

In [13]:
# This neural network attempts to predict 1 of 5 different classes
# We are using batch processing with a batch size of 64
# The output tensor (pred) is of shape (64,5) 
v1,v2 = torch.topk(a,1)

a.shape




torch.Size([64, 5])